---
- name: Provision MERN app server
  hosts: mern
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Node.js & npm
      apt:
        name: nodejs,npm
        state: present

    - name: Install git
      apt:
        name: git
        state: present

    # You can add your own steps here, for example:
    # - clone your backend repo
    # - install dependencies
    # - start your app via systemd or pm2

    - name: Ensure nginx is installed
      apt:
        name: nginx
        state: present

    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: yes
